apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-lending-svc
spec:
  replicas: 3
  selector:
    matchLabels:
      app: test-lending-svc
  template:
    metadata:
      labels:
        app: test-lending-svc
    spec:
      containers:
        - name: test-lending-svc
          image: mrgitau/test-lending-svc:02f84cc18346123980e45d0914688fb89dfec69c
          imagePullPolicy: Always
          ports:
            - containerPort: 8001
