apiVersion: v1
kind: Service
metadata:
  name: test-lending-svc
spec:
  type: NodePort
  selector:
    app: test-lending-svc
  ports:
    - port: 8002
      protocol: TCP
      targetPort: 8099
      nodePort: 31000
