apiVersion: v1
kind: Service
metadata:
  name: test-lending-svc
spec:
  type: NodePort
  selector:
    app: test-lending-svc
  ports:
    - port: 8000
      protocol: TCP
      targetPort: 8001
      nodePort: 31000
