apiVersion: apps/v1
kind: Deployment
metadata:
  name: lending-svc
spec:
  template:
    spec:
      containers:
        - name: test-lending-svc
          image: mrgitau/test-lending-prod-svc:5c3725b



