apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-lending-svc
spec:
  template:
    spec:
      containers:
        - name: test-lending-svc
          image: mrgitau/test-lending-prod-svc:6f9f592
          imagePullPolicy: Always



