apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

namespace: production

patchesStrategicMerge:
  - replicas.yaml
  - image.yaml
  - service-port.yaml

configMapGenerator:
  - name: lending-app-properties
    envs:
      - config.properties