apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: production

replicas:
  - name: test-lending-svc
    count: 5

images:
  - name: mrgitau/test-lending-svc
    newName: mrgitau/test-lending-prod-svc
    newTag: 0d3a701

patchesStrategicMerge:
  - url-links.yaml

configMapGenerator:
  - name: lending-app-properties
    envs:
      - config.properties