apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-lending-svc
spec:
  template:
    spec:
      containers:
        - name: test-lending-svc
          image: mrgitau/test-lending-stage-svc:403fcfd
          imagePullPolicy: Always


