apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: staging

replicas:
  - name: test-lending-svc
    count: 1

images:
  - name: mrgitau/test-lending-svc
    newName: mrgitau/test-lending-stage-svc
    newTag: 403fcfd

patchesStrategicMerge:
  - url-links.yaml

configMapGenerator:
  - name: lending-app-properties
    envs:
      - config.properties
