apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: staging

patchesStrategicMerge:
  - replicas.yaml
  - image.yaml
  - url-links.yaml

configMapGenerator:
  - name: lending-app-properties
    envs:
      - config.properties
