apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

namespace: staging

patchesStrategicMerge:
  - replicas.yaml
  - image.yaml

configMapGenerator:
  - name: lending-app-properties
    envs:
      - config.properties
