apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: rentbureaukenya.com
spec:
  secretName: rentbureaukenya.com
  issuerRef:
    name: letsencrypt-nginx-wcard
    kind: Issuer
    group: cert-manager.io
  commonName: "*.rentbureaukenya.com"
  dnsNames:
    - "rentbureaukenya.com"
    - "*.rentbureaukenya.com"