apiVersion: apps/v1
kind: Deployment
metadata:
  name: lending-svc
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: test-lending-svc
          image: mrgitau/test-lending-svc:cea7f4e
          imagePullPolicy: Always
          ports:
            - containerPort: 8099
          envFrom:
            - configMapRef:
                name: lending-app-properties