apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-lending-svc
spec:
  template:
    spec:
      containers:
        - name: test-lending-svc
          ports:
            - containerPort: 8099
          envFrom:
            - configMapRef:
                name: lending-app-properties