apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - cert-manager-wcard-issuer.yaml
  - cert-manager-wcard-certificate.yaml
  - wildcard-host.yaml

commonLabels:
  app: test-lending-svc

commonAnnotations:
  app: test-lending-svc

