apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml

commonLabels:
  app: lending-svc

commonAnnotations:
  app: test-lending

namePrefix:
  test-
nameSuffix:
  -v1
