apiVersion: v1
kind: Service
metadata:
  name: test-lending-svc
spec:
  type: NodePort
  loadBalancerIP: 139.59.196.150
  externalIPs:
    - 139.59.196.150
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8099
