apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lending-svc-ingress
spec:
  tls:
    - hosts:
        - "*.rentbureaukenya.com"
      secretName: rentbureaukenya.com
  rules:
    - host: production.rentbureaukenya.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: test-lending-svc
                port:
                  number: 80
    - host: transfer.rentbureaukenya.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: test-lending-svc
                port:
                  number: 80
  ingressClassName: nginx
